spring:
  application:
    name: project
  h2:
   console:
    enabled: true
    path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: jaehyun
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
     